name: Docker Build, Push, and Update EKS Deployment

on:
  # push:
  #   branches:
  #     - main  # Trigger on pushes to the main branch. Adjust as needed.
  workflow_dispatch:
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker Build and Push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t beknazar007/todo_app:${{ github.sha }} .
          docker push beknazar007/todo_app:${{ github.sha }}

      # Authenticate with AWS EKS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      # Update Kubernetes deployment with the new image
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/todo-deployment todo=beknazar007/todo_app:${{ github.sha }}
          kubectl rollout status deployment/todo-deployment

# Secrets
# Add your AWS and Docker Hub credentials as secrets in your repository settings
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
