name: Docker Build, Push, and Update EKS Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'html/**'  # Trigger only if changes occur in the html folder

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker Build and Push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t beknazar007/todo_app:${{ github.sha }} .
          docker push beknazar007/todo_app:${{ github.sha }}

      # Authenticate with AWS EKS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      # Update Kubernetes deployment with the new image
      - name: Update Kubernetes deployment
        run: |
          aws eks update-kubeconfig --name qa-eks1-us-east-1a
          kubectl set image deployment/todo-deployment todo=beknazar007/todo_app:${{ github.sha }}
          kubectl rollout status deployment/todo-deployment

