name: Terraform

on:
  # push:
  #   branches:
  #     - main  # Modify as needed
  workflow_dispatch:
    

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        run: |
          cd ~/terraform
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan 

  terraform-apply:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        run:
          cd ~/terraform 
          terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve 