name: Terraform

on:
  # push:
  #   branches:
  #     - main  # Modify as needed
  workflow_dispatch:
    

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan.json
          echo "::set-output name=plan_path::tfplan.json"
          terraform show -json tfplan.json > tfplan.json

      - name: Display Terraform Plan
        run: |
          cat tfplan.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.json
